# Generated by Django 4.0.6 on 2022-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
