# Generated by Django 4.0.6 on 2022-09-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookmark_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
