# Generated by Django 4.0.6 on 2022-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
